// GENERATED by _Kit\sync-kit.ps1 - do not edit by hand.
// Re-run:  .\sync-kit.ps1 -Project CustomerRisk
//
// Lists only the namespaces this project owns. Adding a namespace means
// adding the folder under i18n\ and re-running the sync.

import faCustomerRisk from '@/i18n/customer-risk/fa.json';
import enCustomerRisk from '@/i18n/customer-risk/en.json';

export const DOMAIN_NAMESPACES = {
  fa: {
  'customer-risk': faCustomerRisk,
  },
  en: {
  'customer-risk': enCustomerRisk,
  },
} as const;
